server.port: 9090

lello:
  environment: PRODUCTION
  url:
    production: http://lello.blopez.ec:9090
    development: http://lello.blopez-local.ec:9090
  path: /api/v1.0/

logging:
  file: ./lello.log
  level:
    ROOT: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost/lello?zeroDateTimeBehavior=convertToNull
    username: lello
    password: lello123
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1

esco:
  files:
    skills:
      production: /mnt/lello/src/main/resources/xml/capacities/
      development: ./src/main/resources/xml/capacities/
    occupations:
      production: /mnt/lello/src/main/resources/xml/occupations/
      development: ./src/main/resources/xml/occupations/
    qualifications:
      production: /mnt/lello/src/main/resources/xml/qualifications/
      development: ./src/main/resources/xml/qualifications/
    relationships:
      production: /mnt/lello/src/main/resources/xml/relationships/
      development: ./src/main/resources/xml/relationships/