server.port: 9090

lello:
  environment: PRODUCTION
  url:
    production: http://lello.blopez.ec:9090
    development: http://lello.blopez-local.ec:9090
  path: /api/v1.0/
  crawler.path: data

logging:
  file: ./lello.log
  level:
    ROOT: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost/lello?zeroDateTimeBehavior=convertToNull
    username: lello
    password: lello123
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1

elasticsearch:
  host: localhost
  port: 9300
  cluster:
    name: lello