server.port: 9090

environment: PRODUCTION

logging:
  file: ./lello.log
  level:
    ROOT: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost/lello?zeroDateTimeBehavior=convertToNull
    username: lello
    password: lello123
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1

esco:
  files:
    skills: ./src/main/resources/esco_skills.xml